[package]
name = "lager"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dev-dependencies]
criterion = {version = "0.3.5", features = ["html_reports"]}

[[bench]]
name = "my_benchmark"
harness = false